# Generated by Django 2.2.5 on 2019-11-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField(max_length=650)),
                ('dates_employed', models.CharField(max_length=50)),
                ('languages', models.TextField(max_length=350)),
                ('technologies_used', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=650)),
                ('languages', models.TextField(max_length=350)),
                ('technologies_used', models.TextField(max_length=350)),
            ],
        ),
    ]
