# Generated by Django 2.2.5 on 2019-11-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(default='http://www.github.com/novandev', max_length=350),
        ),
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.URLField(default='http://www.github.com/novandev', max_length=350),
        ),
    ]
